

services:
  db:
    image: postgres:15-alpine
    container_name: sanbou-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: Str0ngP@ss!
      POSTGRES_DB: scribe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
